repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Latest release as of March 14, 2024
    hooks:
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]