---
name: Pre-Commit Checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: pip
      - run: pip install pre-commit
      - run: pip install pylint
      - run: pre-commit run --all-files
