name: Pre-Commit Checks

on:
  push:
  pull_request:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install pre-commit
    - run: pre-commit run --all-files
